### ISSUE TITLE
Parser pat.fullmatch returns None

### ISSUE THREAD

**Issue by Nhrkr** [MystikNinja/whatsapp-parser#2]
Parser returns none for the following contents:
5/3/18, 11:01 PM - +91 95681 00000: bhut logo ne 1 may deposit ni kra hoga 🤓
5/3/18, 11:10 PM - +91 97574 11111 joined using this group's invite link
5/3/18, 11:10 PM - +91 98233 22222 joined using this group's invite link
5/3/18, 11:11 PM - +91 90950 33333 joined using this group's invite link

**Comment by AbhijeetKrishnan** [comment]
Fixed with 358c976adfbdac52eccb1001c531f22334e97559
